In [1]:
import requests # to download html code
from bs4 import BeautifulSoup # to navigate through the html code
import pandas as pd
import numpy as np
import re

In [2]:
url = "https://www.billboard.com/charts/hot-100/"

In [3]:
def scrape_hot100(url_1):
    
    response = requests.get(url_1)
    soup = BeautifulSoup(response.text, 'html.parser')
    if response.status_code == 200:
        artist = []
        title = []
        for elem in soup.select("li.o-chart-results-list__item > span"):
            x = elem.get_text().strip()
            if re.match("\d{1,}|-|NEW|RE-\nENTRY", x):
                pass
            else:
                artist.append(x)
    
    
    
    
        for elem in soup.select("li.o-chart-results-list__item > h3"):
            t = (elem.get_text().strip())
            title.append(t)
    
        titles = pd.DataFrame({"Title" : title})

        artists = pd.DataFrame({"Artist" : artist})

        df = pd.concat([titles, artists], axis = 1)   
    
        return df
    else:
        return print("Page not found")

In [4]:
df = scrape_hot100(url)

In [5]:
df

,Title,Artist
0,Break My Soul,Beyonce
1,As It Was,Harry Styles
2,About Damn Time,Lizzo
3,Running Up That Hill (A Deal With God),Kate Bush
4,Staying Alive,DJ Khaled Featuring Drake & Lil Baby
...,...,...
95,Big 14,"Trippie Redd, Moneybagg Yo & Offset"
96,Until I Found You,Stephen Sanchez
97,Despecha,Rosalia
98,Love Me More,Sam Smith
99,7 Days,YoungBoy Never Broke Again